### ISSUE TITLE
sar:instrument_mode possible values?

### ISSUE THREAD

**Issue by schwehr** [stac-extensions/sar#9]
Not being a SAR expert, where can I find a good list of the sar:instrument_mode values?  I'm seeing `EW`, `IW`, `SM`, and `WV`.

I see https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes

- Stripmap (SM)
- Interferometric Wide swath (IW)
- Extra-Wide swath (EW)
- Wave (WV)

What else is reasonable?

**Comment by m-mohr** [comment]
Yeah, so I remember when I was writing this extension and asked a couple of SAR experts for help, I got like a couple of different answers. So I assume it's difficult, but can't help more although I'm officially co-maintaining this extension.

**Comment by jmorrison1847** [comment]
@schwehr if I have additional product types, what's the best way for me to ask for them to get added? Open a new issue?

On this topic in particular...you've opened quite a can of worms trying to exhaustively log all imaging modes. I think you're off to a good start - if you can catalog everything RADARSAT, TerraSAR-X ([Section 3 in their product guide](https://www.intelligence-airbusds.com/files/pmedia/public/r459_9_20171004_tsxx-airbusds-ma-0009_tsx-productguide_i2.01.pdf)), and COSMO-SkyMed ([Section 2.1.2.1 in their product guide](https://bandiasi.almaviva.it/sites/default/files/attach/scheda-progetto/csk-system-description-users-guide.pdf)), I think you're in pretty good shape. I am not aware of any major newfangled modes that other providers like Capella, ICEYE, or Synspective offer not covered by these big three. I also think it's fair to editorialize and condense things down. You can have a staring spotlight, a mosaicked spotlight, or even a sliding spotlight...but, to me, it's pretty fair to just call all of those spotlight to start.

TerraSAR-X Imaging Modes:
- Staring SpotLight (ST)
- High Resolution SpotLight 300MHz (HS300)
- High Resolution SpotLight (HS)
- SpotLight (SL)
- StripMap (SM)
- ScanSAR (SC)
- Wide ScanSAR (WS)

COSMO-SkyMed Modes:
- Spotlight
- Stripmap
- ScanSAR

**Comment by remi-braun** [comment]
Hello,

I have a [list](https://eoreader.readthedocs.io/en/latest/sar.html#default-resolution) here if needed 🙂 

This is for a lot of sensors but others are missing and every product seems soooo different its a mess 😅

**Comment by emmanuelmathot** [comment]
As already mentionned, the field `sar:intrument_mode` is not a closed values field. This is directly depending on the instrument specified in the `instruments` field and the possible mode of it.
As we can see in the [list](https://eoreader.readthedocs.io/en/latest/sar.html#default-resolution) cited by @remi-braun, many SAR sensors share similar modes. Citing this link in the extension documentation could be interesting.
For very specific modes mentioned by @jmorrison1847, at this point, I would also recommend to use the principal mode to be efficient from the search point of view and thus specific application usage. Also because some of those specific modes can be derived from other fields (e.g. Wide Standard Quad-Pol using the number of polarizations).

**Comment by schwehr** [comment]
I realize these are not enumerated fields.  Was trying to get a sense of what is likely.  Thanks for all the feedback!  I think the text in this issue is great documentation.  That's really what I was looking for.  I'm going to close the issue.  If anyone wants to do more with this, please feel free to reopen it and go nuts.
